---
dependencies:
  flutter:
    sdk: flutter
description: A Flutter package template.
dev_dependencies:
  auto_exporter: ^4.0.0
  build_runner: ^2.0.0
  flutter_lints: any
  flutter_test:
    sdk: flutter
  very_good_analysis: any
environment:
  flutter: '>=1.17.0'
  sdk: ^3.0.0
homepage: https://github.com/normidar/app_lang_selector
name: app_lang_selector
topics:
  - language
  - localization
  - region
  - global
  - globalization
version: 0.0.1
