name: app_lang_selector
description: A Flutter package for easy language selection with beautiful UI and state management support.
version: 0.0.1
homepage: https://github.com/normidar/app_lang_selector
repository: https://github.com/normidar/app_lang_selector
issue_tracker: https://github.com/normidar/app_lang_selector/issues

environment:
  sdk: ^3.0.0
  flutter: '>=1.17.0'

dependencies:
  easy_localization: ^3.0.7
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  riverpod_helper: ^0.0.3

dev_dependencies:
  auto_exporter: any
  build_runner: ^2.4.12
  custom_lint: ^0.7.5
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.6.1
  riverpod_lint: ^2.6.1
  very_good_analysis: any

topics:
  - language
  - localization
  - internationalization
  - i18n
  - ui
  - widget

flutter:
  assets:
    - assets/localizations/
